# Generated by Django 4.2.3 on 2023-10-11 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('session_id', models.CharField(max_length=30)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False, editable=False)),
                ('customer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart records',
                'ordering': ['customer', '-date_ordered'],
            },
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('county', models.CharField(db_column='County/State', max_length=30)),
                ('city', models.CharField(db_column='City/Estate/Town/Village', max_length=30)),
                ('address', models.CharField(max_length=10)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Customer orders records',
                'ordering': ['name', '-date_ordered'],
            },
        ),
        migrations.CreateModel(
            name='RetailStores',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('services', models.CharField(db_column='Services offered', max_length=50)),
                ('address', models.CharField(max_length=40)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('fb_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('ig_url', models.URLField(blank=True)),
                ('image', models.ImageField(default='shop.jpg', upload_to='Retail-Stores/imgs/')),
                ('cover_photo', models.ImageField(default='cover-photo.jpg', upload_to='Retail-Stores/imgs/cover-photos/')),
                ('total_votes', models.PositiveIntegerField(default=0, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Retail Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('feedback', models.TextField()),
                ('crime', models.CharField(max_length=30)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='stores.retailstores')),
            ],
            options={
                'verbose_name_plural': 'Reported stores records',
                'ordering': ['store', '-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('product', models.CharField(db_column='Product Name', max_length=70)),
                ('description', models.TextField()),
                ('rating', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20)),
                ('total_votes', models.PositiveIntegerField(default=0, editable=False)),
                ('img_file', models.ImageField(default='cart.jpeg', upload_to='Products/imgs/')),
                ('out_of_stock', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='stores.retailstores')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['seller', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('voting_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.products')),
                ('store', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.retailstores')),
                ('voter', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Polls',
                'ordering': ['voter', 'voting_date'],
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='stores.products')),
            ],
            options={
                'verbose_name_plural': 'Items in cart',
                'ordering': ['product', '-date_created'],
            },
        ),
    ]
